openapi: 3.1.0
info:
  title: Hyperliquid Info API
  version: 1.0.0
  description: API for querying Hyperliquid Perpetual and Spot info endpoints

servers:
  - url: https://api.hyperliquid.xyz

paths:
  /info:
    post:
      summary: Query Hyperliquid Info Endpoint
      description: |
        POST endpoint to retrieve information about Perpetuals and Spot trading
        on Hyperliquid. Use different JSON bodies with a `type` field to specify requests.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/PerpDexsRequest'
                - $ref: '#/components/schemas/MetaRequest'
                - $ref: '#/components/schemas/MetaAndAssetCtxsRequest'
                - $ref: '#/components/schemas/ClearinghouseStateRequest'
                - $ref: '#/components/schemas/UserFundingRequest'
                - $ref: '#/components/schemas/UserNonFundingLedgerUpdatesRequest'
                - $ref: '#/components/schemas/FundingHistoryRequest'
                - $ref: '#/components/schemas/PredictedFundingsRequest'
                - $ref: '#/components/schemas/PerpsAtOpenInterestCapRequest'
                - $ref: '#/components/schemas/PerpDeployAuctionStatusRequest'
                - $ref: '#/components/schemas/ActiveAssetDataRequest'
                - $ref: '#/components/schemas/SpotMetaRequest'
                - $ref: '#/components/schemas/SpotMetaAndAssetCtxsRequest'
                - $ref: '#/components/schemas/SpotClearinghouseStateRequest'
                - $ref: '#/components/schemas/SpotDeployStateRequest'
                - $ref: '#/components/schemas/TokenDetailsRequest'
                - $ref: '#/components/schemas/L2BookRequest'
      responses:
        '200':
          description: Successful response with requested data
          content:
            application/json:
              schema:
                type: object
                description: Response JSON varies according to request type

components:
  schemas:
    PerpDexsRequest:
      type: object
      properties:
        type:
          type: string
          enum: [perpDexs]
      required:
        - type

    MetaRequest:
      type: object
      properties:
        type:
          type: string
          enum: [meta]
        dex:
          type: string
          description: Perp dex name, optional
      required:
        - type

    MetaAndAssetCtxsRequest:
      type: object
      properties:
        type:
          type: string
          enum: [metaAndAssetCtxs]
      required:
        - type

    ClearinghouseStateRequest:
      type: object
      properties:
        type:
          type: string
          enum: [clearinghouseState]
        user:
          type: string
          description: Onchain address in 42-character hex format
        dex:
          type: string
          description: Perp dex name, optional
      required:
        - type
        - user

    UserFundingRequest:
      type: object
      properties:
        type:
          type: string
          enum: [userFunding]
        user:
          type: string
          description: Onchain address in 42-character hex format
        startTime:
          type: integer
          format: int64
          description: Start time in milliseconds (inclusive)
        endTime:
          type: integer
          format: int64
          description: End time in milliseconds (inclusive)
      required:
        - type
        - user
        - startTime

    UserNonFundingLedgerUpdatesRequest:
      type: object
      properties:
        type:
          type: string
          enum: [userNonFundingLedgerUpdates]
        user:
          type: string
          description: Onchain address in 42-character hex format
        startTime:
          type: integer
          format: int64
          description: Start time in milliseconds (inclusive)
        endTime:
          type: integer
          format: int64
          description: End time in milliseconds (inclusive)
      required:
        - type
        - user
        - startTime

    FundingHistoryRequest:
      type: object
      properties:
        type:
          type: string
          enum: [fundingHistory]
        coin:
          type: string
          description: Coin symbol, eg "ETH"
        startTime:
          type: integer
          format: int64
          description: Start time in milliseconds (inclusive)
        endTime:
          type: integer
          format: int64
          description: End time in milliseconds (inclusive)
      required:
        - type
        - coin
        - startTime

    PredictedFundingsRequest:
      type: object
      properties:
        type:
          type: string
          enum: [predictedFundings]
      required:
        - type

    PerpsAtOpenInterestCapRequest:
      type: object
      properties:
        type:
          type: string
          enum: [perpsAtOpenInterestCap]
        coins:
          type: array
          items:
            type: string
          description: Array of coin symbols
      required:
        - type

    PerpDeployAuctionStatusRequest:
      type: object
      properties:
        type:
          type: string
          enum: [perpDeployAuctionStatus]
      required:
        - type

    ActiveAssetDataRequest:
      type: object
      properties:
        type:
          type: string
          enum: [activeAssetData]
        user:
          type: string
          description: Onchain address in 42-character hex format
        coin:
          type: string
          description: Coin symbol, eg "ETH"
        leverage:
          type: object
          properties:
            type:
              type: string
              description: "leverage type, e.g. 'cross'"
            value:
              type: integer
              description: leverage value
      required:
        - type
        - user
        - coin

    SpotMetaRequest:
      type: object
      properties:
        type:
          type: string
          enum: [spotMeta]
      required:
        - type

    SpotMetaAndAssetCtxsRequest:
      type: object
      properties:
        type:
          type: string
          enum: [spotMetaAndAssetCtxs]
      required:
        - type

    SpotClearinghouseStateRequest:
      type: object
      properties:
        type:
          type: string
          enum: [spotClearinghouseState]
        user:
          type: string
          description: Onchain address in 42-character hex format
      required:
        - type
        - user

    SpotDeployStateRequest:
      type: object
      properties:
        type:
          type: string
          enum: [spotDeployState]
        user:
          type: string
          description: Onchain address in 42-character hex format
      required:
        - type
        - user

    TokenDetailsRequest:
      type: object
      properties:
        type:
          type: string
          enum: [tokenDetails]
        tokenId:
          type: string
          description: Token ID
      required:
        - type
        - tokenId

    L2BookRequest:
      type: object
      properties:
        type:
          type: string
          enum: [l2Book]
        coin:
          type: string
          description: Coin symbol, eg "ETH"
        nSigFigs:
          type: integer
          minimum: 2
          maximum: 5
          description: Aggregates levels to specified significant figures (2-5)
        mantissa:
          type: integer
          enum: [1, 2, 5]
          description: Only allowed if nSigFigs is 5
      required:
        - type
        - coin
